name: Deploy Cloud Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Cloud Functions
        uses: GoogleCloudPlatform/github-actions/deploy-functions@master
        with:
          credentials: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
          project_id: YOUR_PROJECT_ID
          region: us-central1 # Change this to your desired region
          function_name: sayHello 
          source_dir: ./ 
          runtime: nodejs16 
          trigger_http: true

      - name: Save Function URL as an output
        run: echo "FUNCTION_URL=$(gcloud functions describe sayHello --format='value(httpsTrigger.url)')" >> $GITHUB_ENV
