name: Deploy Cloud Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          credentials: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
          project_id: phrasal-marker-400322
          skip_install: true
          version: 'v1.1.1'  

      - name: Authenticate with Google Cloud
        run: |
          echo "$GOOGLE_CLOUD_CREDENTIALS" > /tmp/credentials.json
          gcloud auth activate-service-account --key-file=/tmp/credentials.json
        env:
          GOOGLE_CLOUD_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: pip install gcsfs pandas

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy DataPreprocessing \
            --runtime python310 \
            --trigger-resource keywords_split_five_bucket \
            --trigger-event google.storage.object.finalize \
            --region us-central1 \
            --source=./ \
            --entry-point=main
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}